//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mario.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mario.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Background {
            get {
                return ResourceManager.GetStream("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DeathSound {
            get {
                return ResourceManager.GetStream("DeathSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enemy1 {
            get {
                object obj = ResourceManager.GetObject("Enemy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enemy2 {
            get {
                object obj = ResourceManager.GetObject("Enemy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Jump {
            get {
                return ResourceManager.GetStream("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;level&gt;
        ///
        ///  &lt;!--This is the Enemies --&gt;
        ///  
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt; 
        ///
        ///    &lt;x&gt;500&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///  
        ///  &lt;!--This is the Ending --&gt;
        ///  
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;end&lt;/name&gt; 
        ///
        ///    &lt;x&gt;1075&lt;/x&gt;
        ///
        ///    &lt;y&gt;280&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;!--This is the Powerups --&gt;
        ///  
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;powerup&lt;/name&gt;
        ///
        ///    &lt;x&gt;150&lt;/x&gt;
        ///
        ///    &lt;y&gt;205&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;!--This is the Platforms --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;platform&lt;/name&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;level&gt;
        ///
        ///  &lt;!--This is the Enemies --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;500&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;250&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;750&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;!--This is the Powerups --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;powerup&lt;/name&gt;
        ///
        ///    &lt;x&gt;150&lt;/x&gt;
        ///
        ///    &lt;y&gt;205&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;!--This is the Platfor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;level&gt;
        ///
        ///  &lt;!--This is the Enemies --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;500&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;250&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;750&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;900&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;!--This is the Platforms --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;pl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;level&gt;
        ///
        ///  &lt;!--This is the Enemies --&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;500&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;250&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///  
        ///  &lt;object&gt;
        ///
        ///  &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///  &lt;x&gt;150&lt;/x&gt;
        ///
        ///  &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;750&lt;/x&gt;
        ///
        ///    &lt;y&gt;295&lt;/y&gt;
        ///
        ///  &lt;/object&gt;
        ///
        ///  &lt;object&gt;
        ///
        ///    &lt;name&gt;enemy&lt;/name&gt;
        ///
        ///    &lt;x&gt;900&lt;/x&gt;
        ///
        ///    &lt;y&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mario1 {
            get {
                object obj = ResourceManager.GetObject("Mario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mario2 {
            get {
                object obj = ResourceManager.GetObject("Mario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Platform {
            get {
                object obj = ResourceManager.GetObject("Platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuestionBox {
            get {
                object obj = ResourceManager.GetObject("QuestionBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tunnel {
            get {
                object obj = ResourceManager.GetObject("Tunnel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
